// Generated by node tools/update-cache.mjs. Regenerate after changing a shipped file.
const CACHE="hexa-bloom-a65ccea3bc9c";
const FILES=["./","./CREDITS.md","./assets/audio/bloom.mp3","./assets/audio/clear.mp3","./assets/audio/piano-c4.mp3","./assets/audio/pick.mp3","./assets/audio/place.mp3","./assets/fonts/Nunito.ttf","./assets/fonts/OFL.txt","./assets/icon-192.png","./assets/icon-512.png","./assets/icon.svg","./assets/icons/arrow-right.svg","./assets/icons/arrow-up-right.svg","./assets/icons/chevron-down.svg","./assets/icons/circle-help.svg","./assets/icons/heart.svg","./assets/icons/infinity.svg","./assets/icons/lightbulb.svg","./assets/icons/settings-2.svg","./assets/icons/shuffle.svg","./assets/icons/sun.svg","./assets/icons/trophy.svg","./assets/icons/undo-2.svg","./assets/icons/volume-2.svg","./assets/icons/volume-x.svg","./assets/icons/wand-sparkles.svg","./assets/icons/wifi-off.svg","./assets/icons/x.svg","./assets/licenses/Kenney-MIT.txt","./assets/licenses/Kenney-README.md","./assets/licenses/Lucide.txt","./assets/licenses/Salamander.txt","./index.html","./manifest.webmanifest","./src/audio.js","./src/engine.js","./src/main.js","./src/renderer.js","./src/style.css"];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('hexa-bloom-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{
  const req=event.request,url=new URL(req.url);
  if(req.method!=='GET'||url.origin!==self.location.origin)return;
  event.respondWith((async()=>{
    const cached=await caches.match(req);
    if(cached&&url.pathname.includes('/assets/'))return cached;
    try{const response=await fetch(req);if(response.ok&&FILES.some(f=>new URL(f,self.location.href).pathname===url.pathname)){const cache=await caches.open(CACHE);await cache.put(req,response.clone());}return response;}
    catch(error){if(cached)return cached;if(req.mode==='navigate'){const index=await caches.match(new URL('./index.html',self.location.href));if(index)return index;}throw error;}
  })());
});
