import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,clone,place,neighbors,canPlace,blocked,shuffle,removeStack,dailySeed,goalReached,levelInfo} from '../src/engine.js';
const count=s=>s.cells.reduce((n,c)=>n+c.stack.length,0);
function blank(level=1){const s=createGame(level);s.cells.forEach(c=>Object.assign(c,{stack:[],rock:0,flower:false,bloomed:false,sun:false}));return s;}
function index(s,q,r){return s.cells.findIndex(c=>c.q===q&&c.r===r);}
test('hex geometry has 19 or 37 cells and symmetric adjacency',()=>{for(const level of [1,25]){const s=createGame(level);assert.equal(s.cells.length,level===1?19:37);for(let i=0;i<s.cells.length;i++)for(const j of neighbors(s.cells,i))assert.ok(neighbors(s.cells,j).includes(i));assert.equal(neighbors(s.cells,index(s,0,0)).length,6);}});
test('placement rejects rocks, occupied cells and missing offers without mutation',()=>{const s=createGame(7);const before=clone(s);assert.equal(place(s,0,s.cells.findIndex(c=>c.stack.length)),null);assert.equal(place(s,0,s.cells.findIndex(c=>c.rock)),null);assert.equal(place(s,99,s.cells.findIndex((c,i)=>canPlace(s,i))),null);assert.deepEqual(s,before);});
test('ten matching pieces clear, score, and preserve all other colors',()=>{const s=blank();const a=index(s,0,0),b=index(s,1,0);s.cells[a].stack=[1,1,0,0,0,0];s.hand[0]=Array(6).fill(0);const r=place(s,0,b);assert.equal(r.combo,1);assert.equal(s.score,100);assert.equal(s.cleared,10);assert.deepEqual(s.cells[a].stack,[1,1]);assert.equal(s.cells[b].stack.length,0);});
test('revealed colors cause a real cascade with increasing multiplier',()=>{const s=blank(3);const a=index(s,0,0),b=index(s,1,0);s.cells[a].stack=[...Array(4).fill(1),...Array(4).fill(0)];s.hand[0]=[...Array(6).fill(1),...Array(6).fill(0)];const result=place(s,0,b);assert.equal(result.combo,2);assert.equal(s.score,300);assert.equal(s.cleared,20);assert.equal(count(s),0);assert.equal(s.bestCombo,2);});
test('flowers attract a merge and bloom; adjacent stone loses one layer',()=>{const s=blank(19),a=index(s,0,0),b=index(s,1,0),stone=index(s,0,1);s.cells[a].flower=true;s.cells[a].stack=Array(4).fill(0);s.cells[a].sun=true;s.cells[stone].rock=2;s.hand[0]=Array(6).fill(0);place(s,0,b);assert.equal(s.flowers,1);assert.equal(s.cells[a].bloomed,true);assert.equal(s.cells[stone].rock,1);assert.equal(s.score,200);});
test('joker adopts adjacent top color',()=>{const s=blank(10),a=index(s,0,0),b=index(s,1,0);s.cells[a].stack=Array(6).fill(2);s.hand[0]=Array(4).fill(-1);place(s,0,b);assert.equal(s.harvest[2],10);assert.equal(s.score,100);});
test('victory requires score, flowers and harvest together',()=>{const s=createGame(13),info=levelInfo(13);s.score=info.target;assert.equal(goalReached(s),false);s.flowers=info.flowers;assert.equal(goalReached(s),false);s.harvest[info.harvest.color]=info.harvest.target;assert.equal(goalReached(s),true);assert.equal(goalReached({...s,mode:'zen'}),false);});
test('daily seed and all offers reproduce exactly',()=>{assert.equal(dailySeed('2026-10-07'),dailySeed('2026-10-07'));assert.notEqual(dailySeed('2026-10-07'),dailySeed('2026-10-08'));const a=createGame(1,'daily',dailySeed('2026-10-07')),b=clone(a);for(let n=0;n<10;n++){const i=a.cells.findIndex((_,i)=>canPlace(a,i));if(i<0)break;place(a,n%3,i);place(b,n%3,i);}assert.deepEqual(a,b);});
test('brassages and éclaircies consume and replenish free resources',()=>{const s=blank(),i=index(s,0,0);assert.ok(shuffle(s));assert.equal(s.shuffles,2);s.cells[i].stack=[1,1,1];assert.ok(removeStack(s,i));assert.equal(s.spades,1);assert.equal(s.cells[i].stack.length,0);assert.equal(removeStack(s,i),false);s.moves=3;s.hand[0]=[0];place(s,0,i);assert.equal(s.shuffles,3);});
test('many randomized runs conserve pieces and resolve all matching neighbors',()=>{for(let level=1;level<=30;level++){const s=createGame(level);for(let move=0;move<20&&!s.ended;move++){const legal=s.cells.map((_,i)=>i).filter(i=>canPlace(s,i));if(!legal.length)break;const h=move%3,before=count(s),added=s.hand[h].length,cleared=s.cleared;const result=place(s,h,legal[(move*7)%legal.length]);assert.ok(result.events.length<250);assert.equal(count(s)+s.cleared-cleared,before+added);for(let i=0;i<s.cells.length;i++)if(s.cells[i].stack.length)for(const j of neighbors(s.cells,i))if(s.cells[j].stack.length)assert.notEqual(s.cells[i].stack.at(-1),s.cells[j].stack.at(-1));}}});
test('a full board is detected, and an éclaircie restores a legal move',()=>{const s=blank();s.cells.forEach((c,i)=>c.stack=[i%3]);assert.equal(blocked(s),true);assert.ok(removeStack(s,0));assert.equal(blocked(s),false);});
